
spring:
  profiles:
    include: openhab
  application:
    name: Marvin the Robot
    version: 0.0.1
  ai:
    openai:
      api-key: ${OPENAI_APIKEY} # OpenAI API key, get your own at https://platform.openai.com
    vectorstore:
      pgvector:
        initialize-schema: false
        index-type: hnsw
        distance-type: cosine_distance
        dimensions: 1536
        remove-existing-vector-store-table: false
  datasource:
    url: jdbc:postgresql://${VECTORDB_ADDRESS}:5555/vectordb
    username: testuser
    password: testpwd

server:
  port: 9090

openhab:
  url: ${OPENHAB_URL}
  username: ${OPENHAB_USERNAME}
  password: ${OPENHAB_PASSWORD}

logging:
  include-application-name: true

google:
  apikey: ${GOOGLE_APIKEY}
  cx: ${GOOGLE_CX}
