spring:
  profiles:
    include: openhab, gemini
  application:
    name: Marvin the Robot
    version: 0.0.1
  ai:
    vectorstore:
      cassandra:
        initialize-schema: true
    openai:
      api-key: ${OPENAI_APIKEY} # OpenAI API key, get your own at https://platform.openai.com
      chat:
        enabled: false
    vertex:
      ai:
        gemini:
            #AIzaSyABBB9BvU2wunNQesvLmy8Myx_ghssoiok
          project-id: marvin-442314
          location: europe-west2
          api-endpoint: europe-north1-aiplatform.googleapis.com

  cassandra:
    local-datacenter: datacenter1
    keyspace-name: springframework
    contact-points: ${VECTORDB_ADDRESS}
    password: admin
    username: admin
    schema-action: create_if_not_exists
  security:
    oauth2:
      client:
        registration:
          github:
            redirect-uri: ${EXTERNAL_ADDRESS}/login/oauth2/code/github
            clientId: ${GITHUB_CLIENT_ID}
            clientSecret: ${GITHUB_CLIENT_SECRET}
server:
  port: 9090

openhab:
  url: ${OPENHAB_URL}
  username: ${OPENHAB_USERNAME}
  password: ${OPENHAB_PASSWORD}

logging:
  include-application-name: true

google:
  apikey: ${GOOGLE_APIKEY}
  cx: ${GOOGLE_CX}

marvin:
  language: 'en'
