spring:
  profiles:
    include:
      - environment-openhab
      - chat-openai
      - library-bookstack
  application:
    name: Marvin the Robot
    version: 0.0.1
  ai:
    vectorstore:
      cassandra:
        initialize-schema: true
    openai:
      api-key: ${OPENAI_APIKEY} # OpenAI API key, get your own at https://platform.openai.com
  cassandra:
    local-datacenter: datacenter1
    keyspace-name: springframework
    contact-points: ${VECTORDB_ADDRESS}
    password: admin
    username: admin
    schema-action: create_if_not_exists
  security:
    oauth2:
      client:
        registration:
          github:
            redirect-uri: ${EXTERNAL_ADDRESS}/login/oauth2/code/github
            clientId: ${GITHUB_CLIENT_ID}
            clientSecret: ${GITHUB_CLIENT_SECRET}
          google:
            scope:
              - email
              - profile
            redirect-uri: ${EXTERNAL_ADDRESS}/login/oauth2/code/google
            clientId: ${GOOGLE_CLIENT_ID}
            clientSecret: ${GOOGLE_CLIENT_SECRET}
server:
  port: 9090

openhab:
  url: ${OPENHAB_URL}
  username: ${OPENHAB_USERNAME}
  password: ${OPENHAB_PASSWORD}

logging:
  include-application-name: true

google:
  apikey: ${GOOGLE_APIKEY}
  cx: ${GOOGLE_CX}

bookstack:
  url: ${BOOKSTACK_URL}
  tokenid: ${BOOKSTACK_TOKEN_ID}
  tokensecret: ${BOOKSTACK_TOKEN_SECRET}

marvin:
  language: 'en'
