name: CI

on:
  push:
    branches:
      - master   # Run only on pushes to the main branch
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'
          cache: maven  # Enable dependency caching for faster builds

      - name: Build and test
        run: mvn clean install
