name: CI

on:
  push:
    branches:
      - master   # Run only on pushes to the main branch
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'
          cache: maven  # Enable dependency caching for faster builds

      - name: build the app
        run: |
          mvn clean
          mvn -B package --file pom.xml
      - name: build the docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          dockerfile: docker/Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/marvin:latest

      - name: login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: push the docker image to docker hub
        uses: docker/build-push-action@v4
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/marvin:latest